/**
 * Portrait image mapping for philosophers.
 * Generated by scripts/fetch_portraits.py + scripts/process_images.py
 * Keys are Philosopher.id, values are { thumb, large } paths relative to /public.
 */

export const philosopherPortraits: Record<string, { thumb: string; large: string }> = {
  // Ancient Greece
  plato: {
    thumb: "/images/philosophers/plato_thumb.webp",
    large: "/images/philosophers/plato_large.webp",
  },
  aristotle: {
    thumb: "/images/philosophers/aristotle_thumb.webp",
    large: "/images/philosophers/aristotle_large.webp",
  },
  // Modern Western
  descartes: {
    thumb: "/images/philosophers/rene_descartes_thumb.webp",
    large: "/images/philosophers/rene_descartes_large.webp",
  },
  kant: {
    thumb: "/images/philosophers/immanuel_kant_thumb.webp",
    large: "/images/philosophers/immanuel_kant_large.webp",
  },
  nietzche: {
    thumb: "/images/philosophers/friedrich_nietzsche_thumb.webp",
    large: "/images/philosophers/friedrich_nietzsche_large.webp",
  },
  // Chinese
  confucius: {
    thumb: "/images/philosophers/confucius_thumb.webp",
    large: "/images/philosophers/confucius_large.webp",
  },
  laozi: {
    thumb: "/images/philosophers/laozi_thumb.webp",
    large: "/images/philosophers/laozi_large.webp",
  },
  zhuangzi: {
    thumb: "/images/philosophers/zhuangzi_thumb.webp",
    large: "/images/philosophers/zhuangzi_large.webp",
  },
};

export function getPhilosopherPortrait(id: string): { thumb: string; large: string } | undefined {
  return philosopherPortraits[id];
}
