/**
 * Portrait image mapping for philosophers.
 * Auto-generated by scripts/generate_portrait_map.py
 * Total: 76 philosophers with portraits
 */

export const philosopherPortraits: Record<string, { thumb: string; large: string }> = {
  albertus: {
    thumb: "/images/philosophers/albertus_magnus_thumb.webp",
    large: "/images/philosophers/albertus_magnus_large.webp",
  },
  kant: {
    thumb: "/images/philosophers/immanuel_kant_thumb.webp",
    large: "/images/philosophers/immanuel_kant_large.webp",
  },
  nietzche: {
    thumb: "/images/philosophers/friedrich_nietzsche_thumb.webp",
    large: "/images/philosophers/friedrich_nietzsche_large.webp",
  },
  antisthenes: {
    thumb: "/images/philosophers/antisthenes_thumb.webp",
    large: "/images/philosophers/antisthenes_large.webp",
  },
  aquinas: {
    thumb: "/images/philosophers/thomas_aquinas_thumb.webp",
    large: "/images/philosophers/thomas_aquinas_large.webp",
  },
  aristotle: {
    thumb: "/images/philosophers/aristotle_thumb.webp",
    large: "/images/philosophers/aristotle_large.webp",
  },
  averroes: {
    thumb: "/images/philosophers/averroe_thumb.webp",
    large: "/images/philosophers/averroe_large.webp",
  },
  berengar: {
    thumb: "/images/philosophers/berengar_de_tours_thumb.webp",
    large: "/images/philosophers/berengar_de_tours_large.webp",
  },
  calvin: {
    thumb: "/images/philosophers/calvin_thumb.webp",
    large: "/images/philosophers/calvin_large.webp",
  },
  cheng_hao: {
    thumb: "/images/philosophers/cheng_hao_thumb.webp",
    large: "/images/philosophers/cheng_hao_large.webp",
  },
  chrysippus: {
    thumb: "/images/philosophers/chrysippus_thumb.webp",
    large: "/images/philosophers/chrysippus_large.webp",
  },
  cicero: {
    thumb: "/images/philosophers/cicero_thumb.webp",
    large: "/images/philosophers/cicero_large.webp",
  },
  cleanthes: {
    thumb: "/images/philosophers/cleanthes_thumb.webp",
    large: "/images/philosophers/cleanthes_large.webp",
  },
  comte: {
    thumb: "/images/philosophers/comte_thumb.webp",
    large: "/images/philosophers/comte_large.webp",
  },
  confucius: {
    thumb: "/images/philosophers/confucius_thumb.webp",
    large: "/images/philosophers/confucius_large.webp",
  },
  democritus: {
    thumb: "/images/philosophers/democritus_thumb.webp",
    large: "/images/philosophers/democritus_large.webp",
  },
  descartes: {
    thumb: "/images/philosophers/descartes_thumb.webp",
    large: "/images/philosophers/descartes_large.webp",
  },
  dewey: {
    thumb: "/images/philosophers/john_dewey_thumb.webp",
    large: "/images/philosophers/john_dewey_large.webp",
  },
  diderot: {
    thumb: "/images/philosophers/diderot_thumb.webp",
    large: "/images/philosophers/diderot_large.webp",
  },
  diogenes: {
    thumb: "/images/philosophers/diogenes_thumb.webp",
    large: "/images/philosophers/diogenes_large.webp",
  },
  empedocles: {
    thumb: "/images/philosophers/empedocles_thumb.webp",
    large: "/images/philosophers/empedocles_large.webp",
  },
  epicurus: {
    thumb: "/images/philosophers/epicurus_thumb.webp",
    large: "/images/philosophers/epicurus_large.webp",
  },
  eriugena: {
    thumb: "/images/philosophers/eriugena_thumb.webp",
    large: "/images/philosophers/eriugena_large.webp",
  },
  euclides_meg: {
    thumb: "/images/philosophers/euclides_thumb.webp",
    large: "/images/philosophers/euclides_large.webp",
  },
  ficino: {
    thumb: "/images/philosophers/marsilio_ficino_thumb.webp",
    large: "/images/philosophers/marsilio_ficino_large.webp",
  },
  gassendi: {
    thumb: "/images/philosophers/pierre_gassendi_thumb.webp",
    large: "/images/philosophers/pierre_gassendi_large.webp",
  },
  gongsun_long: {
    thumb: "/images/philosophers/gongsun_long_thumb.webp",
    large: "/images/philosophers/gongsun_long_large.webp",
  },
  gu_yanwu: {
    thumb: "/images/philosophers/gu_yanwu_thumb.webp",
    large: "/images/philosophers/gu_yanwu_large.webp",
  },
  hegel: {
    thumb: "/images/philosophers/hegel_thumb.webp",
    large: "/images/philosophers/hegel_large.webp",
  },
  heraclitus: {
    thumb: "/images/philosophers/heraclitus_thumb.webp",
    large: "/images/philosophers/heraclitus_large.webp",
  },
  herbert_cher: {
    thumb: "/images/philosophers/herbert_of_cherbury_thumb.webp",
    large: "/images/philosophers/herbert_of_cherbury_large.webp",
  },
  hume: {
    thumb: "/images/philosophers/hume_thumb.webp",
    large: "/images/philosophers/hume_large.webp",
  },
  husserl: {
    thumb: "/images/philosophers/edmund_husserl_thumb.webp",
    large: "/images/philosophers/edmund_husserl_large.webp",
  },
  kang_youwei: {
    thumb: "/images/philosophers/kang_youwei_thumb.webp",
    large: "/images/philosophers/kang_youwei_large.webp",
  },
  kierkegaard: {
    thumb: "/images/philosophers/kierkegaard_thumb.webp",
    large: "/images/philosophers/kierkegaard_large.webp",
  },
  laozi: {
    thumb: "/images/philosophers/laozi_thumb.webp",
    large: "/images/philosophers/laozi_large.webp",
  },
  leibniz: {
    thumb: "/images/philosophers/leibniz_thumb.webp",
    large: "/images/philosophers/leibniz_large.webp",
  },
  liang_qichao: {
    thumb: "/images/philosophers/liang_qichao_thumb.webp",
    large: "/images/philosophers/liang_qichao_large.webp",
  },
  locke: {
    thumb: "/images/philosophers/locke_thumb.webp",
    large: "/images/philosophers/locke_large.webp",
  },
  luther: {
    thumb: "/images/philosophers/martin_luther_thumb.webp",
    large: "/images/philosophers/martin_luther_large.webp",
  },
  marcus_aurelius: {
    thumb: "/images/philosophers/marcus_aurelius_thumb.webp",
    large: "/images/philosophers/marcus_aurelius_large.webp",
  },
  marx: {
    thumb: "/images/philosophers/karl_marx_thumb.webp",
    large: "/images/philosophers/karl_marx_large.webp",
  },
  mill_j: {
    thumb: "/images/philosophers/mill_thumb.webp",
    large: "/images/philosophers/mill_large.webp",
  },
  montaigne: {
    thumb: "/images/philosophers/montaigne_thumb.webp",
    large: "/images/philosophers/montaigne_large.webp",
  },
  more: {
    thumb: "/images/philosophers/thomas_more_thumb.webp",
    large: "/images/philosophers/thomas_more_large.webp",
  },
  petrarca: {
    thumb: "/images/philosophers/francesco_petrarca_thumb.webp",
    large: "/images/philosophers/francesco_petrarca_large.webp",
  },
  philo: {
    thumb: "/images/philosophers/philo_thumb.webp",
    large: "/images/philosophers/philo_large.webp",
  },
  pico: {
    thumb: "/images/philosophers/giovanni_pico_thumb.webp",
    large: "/images/philosophers/giovanni_pico_large.webp",
  },
  plato: {
    thumb: "/images/philosophers/plato_thumb.webp",
    large: "/images/philosophers/plato_large.webp",
  },
  plotinus: {
    thumb: "/images/philosophers/plotinus_thumb.webp",
    large: "/images/philosophers/plotinus_large.webp",
  },
  pythagoras: {
    thumb: "/images/philosophers/pythagoras_thumb.webp",
    large: "/images/philosophers/pythagoras_large.webp",
  },
  roger_bacon: {
    thumb: "/images/philosophers/roger_bacon_thumb.webp",
    large: "/images/philosophers/roger_bacon_large.webp",
  },
  rorty: {
    thumb: "/images/philosophers/richard_rorty_thumb.webp",
    large: "/images/philosophers/richard_rorty_large.webp",
  },
  rousseau: {
    thumb: "/images/philosophers/rousseau_thumb.webp",
    large: "/images/philosophers/rousseau_large.webp",
  },
  ruan_ji: {
    thumb: "/images/philosophers/ruan_ji_thumb.webp",
    large: "/images/philosophers/ruan_ji_large.webp",
  },
  russell: {
    thumb: "/images/philosophers/bertrand_russell_thumb.webp",
    large: "/images/philosophers/bertrand_russell_large.webp",
  },
  sartre: {
    thumb: "/images/philosophers/jean-paul_sartre_thumb.webp",
    large: "/images/philosophers/jean-paul_sartre_large.webp",
  },
  schelling: {
    thumb: "/images/philosophers/schelling_thumb.webp",
    large: "/images/philosophers/schelling_large.webp",
  },
  schopenhauer: {
    thumb: "/images/philosophers/schopenhauer_thumb.webp",
    large: "/images/philosophers/schopenhauer_large.webp",
  },
  scotus: {
    thumb: "/images/philosophers/johannes_duns_scotus_thumb.webp",
    large: "/images/philosophers/johannes_duns_scotus_large.webp",
  },
  seneca: {
    thumb: "/images/philosophers/seneca_thumb.webp",
    large: "/images/philosophers/seneca_large.webp",
  },
  shao_yong: {
    thumb: "/images/philosophers/shao_yong_thumb.webp",
    large: "/images/philosophers/shao_yong_large.webp",
  },
  spencer: {
    thumb: "/images/philosophers/spencer_thumb.webp",
    large: "/images/philosophers/spencer_large.webp",
  },
  strauss: {
    thumb: "/images/philosophers/david_strauss_thumb.webp",
    large: "/images/philosophers/david_strauss_large.webp",
  },
  thales: {
    thumb: "/images/philosophers/thales_thumb.webp",
    large: "/images/philosophers/thales_large.webp",
  },
  voltaire: {
    thumb: "/images/philosophers/voltaire_thumb.webp",
    large: "/images/philosophers/voltaire_large.webp",
  },
  wang_fuzhi: {
    thumb: "/images/philosophers/wang_fuzhi_thumb.webp",
    large: "/images/philosophers/wang_fuzhi_large.webp",
  },
  xuanzang: {
    thumb: "/images/philosophers/xuanzang_thumb.webp",
    large: "/images/philosophers/xuanzang_large.webp",
  },
  yan_fu: {
    thumb: "/images/philosophers/yan_fu_thumb.webp",
    large: "/images/philosophers/yan_fu_large.webp",
  },
  yang_xiong: {
    thumb: "/images/philosophers/yang_xiong_thumb.webp",
    large: "/images/philosophers/yang_xiong_large.webp",
  },
  zeno: {
    thumb: "/images/philosophers/zenon_thumb.webp",
    large: "/images/philosophers/zenon_large.webp",
  },
  zeno_citium: {
    thumb: "/images/philosophers/zeno_thumb.webp",
    large: "/images/philosophers/zeno_large.webp",
  },
  zhiyi: {
    thumb: "/images/philosophers/zhiyi_thumb.webp",
    large: "/images/philosophers/zhiyi_large.webp",
  },
  zhou_dunyi: {
    thumb: "/images/philosophers/zhou_dunyi_thumb.webp",
    large: "/images/philosophers/zhou_dunyi_large.webp",
  },
  zhu_xi: {
    thumb: "/images/philosophers/zhu_xi_thumb.webp",
    large: "/images/philosophers/zhu_xi_large.webp",
  },
  zhuangzi: {
    thumb: "/images/philosophers/zhuangzi_thumb.webp",
    large: "/images/philosophers/zhuangzi_large.webp",
  },
};

export function getPhilosopherPortrait(id: string): { thumb: string; large: string } | undefined {
  return philosopherPortraits[id];
}
