/**
 * Portrait image mapping for philosophers.
 * Auto-generated by scripts/generate_portrait_map.py
 * Total: 109 philosophers with portraits
 */

export const philosopherPortraits: Record<string, { thumb: string; large: string }> = {
  albertus: {
    thumb: "/images/philosophers/albertus_magnus_thumb.webp",
    large: "/images/philosophers/albertus_magnus_large.webp",
  },
  anaxagoras: {
    thumb: "/images/philosophers/anaxagoras_thumb.webp",
    large: "/images/philosophers/anaxagoras_large.webp",
  },
  anselm: {
    thumb: "/images/philosophers/anselmus_thumb.webp",
    large: "/images/philosophers/anselmus_large.webp",
  },
  antisthenes: {
    thumb: "/images/philosophers/antisthenes_thumb.webp",
    large: "/images/philosophers/antisthenes_large.webp",
  },
  aquinas: {
    thumb: "/images/philosophers/thomas_aquinas_thumb.webp",
    large: "/images/philosophers/thomas_aquinas_large.webp",
  },
  aristippus: {
    thumb: "/images/philosophers/aristippus_thumb.webp",
    large: "/images/philosophers/aristippus_large.webp",
  },
  aristotle: {
    thumb: "/images/philosophers/aristotle_thumb.webp",
    large: "/images/philosophers/aristotle_large.webp",
  },
  averroes: {
    thumb: "/images/philosophers/averroe_thumb.webp",
    large: "/images/philosophers/averroe_large.webp",
  },
  bacon_f: {
    thumb: "/images/philosophers/francis_bacon_thumb.webp",
    large: "/images/philosophers/francis_bacon_large.webp",
  },
  berengar: {
    thumb: "/images/philosophers/berengar_de_tours_thumb.webp",
    large: "/images/philosophers/berengar_de_tours_large.webp",
  },
  calvin: {
    thumb: "/images/philosophers/calvin_thumb.webp",
    large: "/images/philosophers/calvin_large.webp",
  },
  chen_liang: {
    thumb: "/images/philosophers/chen_liang_thumb.webp",
    large: "/images/philosophers/chen_liang_large.webp",
  },
  cheng_hao: {
    thumb: "/images/philosophers/cheng_hao_thumb.webp",
    large: "/images/philosophers/cheng_hao_large.webp",
  },
  cheng_yi: {
    thumb: "/images/philosophers/cheng_yi_thumb.webp",
    large: "/images/philosophers/cheng_yi_large.webp",
  },
  chrysippus: {
    thumb: "/images/philosophers/chrysippus_thumb.webp",
    large: "/images/philosophers/chrysippus_large.webp",
  },
  cicero: {
    thumb: "/images/philosophers/cicero_thumb.webp",
    large: "/images/philosophers/cicero_large.webp",
  },
  cleanthes: {
    thumb: "/images/philosophers/cleanthes_thumb.webp",
    large: "/images/philosophers/cleanthes_large.webp",
  },
  comte: {
    thumb: "/images/philosophers/comte_thumb.webp",
    large: "/images/philosophers/comte_large.webp",
  },
  confucius: {
    thumb: "/images/philosophers/confucius_thumb.webp",
    large: "/images/philosophers/confucius_large.webp",
  },
  dai_zhen: {
    thumb: "/images/philosophers/dai_zhen_thumb.webp",
    large: "/images/philosophers/dai_zhen_large.webp",
  },
  democritus: {
    thumb: "/images/philosophers/democritus_thumb.webp",
    large: "/images/philosophers/democritus_large.webp",
  },
  derrida: {
    thumb: "/images/philosophers/jacques_derrida_thumb.webp",
    large: "/images/philosophers/jacques_derrida_large.webp",
  },
  descartes: {
    thumb: "/images/philosophers/descartes_thumb.webp",
    large: "/images/philosophers/descartes_large.webp",
  },
  dewey: {
    thumb: "/images/philosophers/john_dewey_thumb.webp",
    large: "/images/philosophers/john_dewey_large.webp",
  },
  diderot: {
    thumb: "/images/philosophers/diderot_thumb.webp",
    large: "/images/philosophers/diderot_large.webp",
  },
  diogenes: {
    thumb: "/images/philosophers/diogenes_thumb.webp",
    large: "/images/philosophers/diogenes_large.webp",
  },
  dong_zhongshu: {
    thumb: "/images/philosophers/dong_zhongshu_thumb.webp",
    large: "/images/philosophers/dong_zhongshu_large.webp",
  },
  empedocles: {
    thumb: "/images/philosophers/empedocles_thumb.webp",
    large: "/images/philosophers/empedocles_large.webp",
  },
  epictetus: {
    thumb: "/images/philosophers/epictetus_thumb.webp",
    large: "/images/philosophers/epictetus_large.webp",
  },
  epicurus: {
    thumb: "/images/philosophers/epicurus_thumb.webp",
    large: "/images/philosophers/epicurus_large.webp",
  },
  eriugena: {
    thumb: "/images/philosophers/eriugena_thumb.webp",
    large: "/images/philosophers/eriugena_large.webp",
  },
  euclides_meg: {
    thumb: "/images/philosophers/euclides_thumb.webp",
    large: "/images/philosophers/euclides_large.webp",
  },
  ficino: {
    thumb: "/images/philosophers/marsilio_ficino_thumb.webp",
    large: "/images/philosophers/marsilio_ficino_large.webp",
  },
  foucault: {
    thumb: "/images/philosophers/michel_foucault_thumb.webp",
    large: "/images/philosophers/michel_foucault_large.webp",
  },
  gassendi: {
    thumb: "/images/philosophers/pierre_gassendi_thumb.webp",
    large: "/images/philosophers/pierre_gassendi_large.webp",
  },
  gongsun_long: {
    thumb: "/images/philosophers/gongsun_long_thumb.webp",
    large: "/images/philosophers/gongsun_long_large.webp",
  },
  gu_yanwu: {
    thumb: "/images/philosophers/gu_yanwu_thumb.webp",
    large: "/images/philosophers/gu_yanwu_large.webp",
  },
  hegel: {
    thumb: "/images/philosophers/hegel_thumb.webp",
    large: "/images/philosophers/hegel_large.webp",
  },
  helvetius: {
    thumb: "/images/philosophers/helvetius_thumb.webp",
    large: "/images/philosophers/helvetius_large.webp",
  },
  heraclitus: {
    thumb: "/images/philosophers/heraclitus_thumb.webp",
    large: "/images/philosophers/heraclitus_large.webp",
  },
  herbert_cher: {
    thumb: "/images/philosophers/herbert_of_cherbury_thumb.webp",
    large: "/images/philosophers/herbert_of_cherbury_large.webp",
  },
  hobbes: {
    thumb: "/images/philosophers/hobbes_thumb.webp",
    large: "/images/philosophers/hobbes_large.webp",
  },
  holbach: {
    thumb: "/images/philosophers/holbach_thumb.webp",
    large: "/images/philosophers/holbach_large.webp",
  },
  hu_shi: {
    thumb: "/images/philosophers/hu_shi_thumb.webp",
    large: "/images/philosophers/hu_shi_large.webp",
  },
  huineng: {
    thumb: "/images/philosophers/huineng_thumb.webp",
    large: "/images/philosophers/huineng_large.webp",
  },
  hume: {
    thumb: "/images/philosophers/hume_thumb.webp",
    large: "/images/philosophers/hume_large.webp",
  },
  husserl: {
    thumb: "/images/philosophers/edmund_husserl_thumb.webp",
    large: "/images/philosophers/edmund_husserl_large.webp",
  },
  kang_youwei: {
    thumb: "/images/philosophers/kang_youwei_thumb.webp",
    large: "/images/philosophers/kang_youwei_large.webp",
  },
  kant: {
    thumb: "/images/philosophers/kant_thumb.webp",
    large: "/images/philosophers/kant_large.webp",
  },
  kierkegaard: {
    thumb: "/images/philosophers/kierkegaard_thumb.webp",
    large: "/images/philosophers/kierkegaard_large.webp",
  },
  laozi: {
    thumb: "/images/philosophers/laozi_thumb.webp",
    large: "/images/philosophers/laozi_large.webp",
  },
  leibniz: {
    thumb: "/images/philosophers/leibniz_thumb.webp",
    large: "/images/philosophers/leibniz_large.webp",
  },
  liang_qichao: {
    thumb: "/images/philosophers/liang_qichao_thumb.webp",
    large: "/images/philosophers/liang_qichao_large.webp",
  },
  liu_zongzhou: {
    thumb: "/images/philosophers/liu_zongzhou_thumb.webp",
    large: "/images/philosophers/liu_zongzhou_large.webp",
  },
  locke: {
    thumb: "/images/philosophers/locke_thumb.webp",
    large: "/images/philosophers/locke_large.webp",
  },
  luther: {
    thumb: "/images/philosophers/martin_luther_thumb.webp",
    large: "/images/philosophers/martin_luther_large.webp",
  },
  malebranche: {
    thumb: "/images/philosophers/malebranche_thumb.webp",
    large: "/images/philosophers/malebranche_large.webp",
  },
  marcus_aurelius: {
    thumb: "/images/philosophers/marcus_aurelius_thumb.webp",
    large: "/images/philosophers/marcus_aurelius_large.webp",
  },
  marx: {
    thumb: "/images/philosophers/karl_marx_thumb.webp",
    large: "/images/philosophers/karl_marx_large.webp",
  },
  mettrie: {
    thumb: "/images/philosophers/la_mettrie_thumb.webp",
    large: "/images/philosophers/la_mettrie_large.webp",
  },
  mill_j: {
    thumb: "/images/philosophers/mill_thumb.webp",
    large: "/images/philosophers/mill_large.webp",
  },
  montaigne: {
    thumb: "/images/philosophers/montaigne_thumb.webp",
    large: "/images/philosophers/montaigne_large.webp",
  },
  more: {
    thumb: "/images/philosophers/thomas_more_thumb.webp",
    large: "/images/philosophers/thomas_more_large.webp",
  },
  nietzche: {
    thumb: "/images/philosophers/nietzsche_thumb.webp",
    large: "/images/philosophers/nietzsche_large.webp",
  },
  parmenides: {
    thumb: "/images/philosophers/parmenides_thumb.webp",
    large: "/images/philosophers/parmenides_large.webp",
  },
  peirce: {
    thumb: "/images/philosophers/charles_sanders_peirce_thumb.webp",
    large: "/images/philosophers/charles_sanders_peirce_large.webp",
  },
  petrarca: {
    thumb: "/images/philosophers/francesco_petrarca_thumb.webp",
    large: "/images/philosophers/francesco_petrarca_large.webp",
  },
  philo: {
    thumb: "/images/philosophers/philo_thumb.webp",
    large: "/images/philosophers/philo_large.webp",
  },
  pico: {
    thumb: "/images/philosophers/giovanni_pico_thumb.webp",
    large: "/images/philosophers/giovanni_pico_large.webp",
  },
  plato: {
    thumb: "/images/philosophers/plato_thumb.webp",
    large: "/images/philosophers/plato_large.webp",
  },
  plotinus: {
    thumb: "/images/philosophers/plotinus_thumb.webp",
    large: "/images/philosophers/plotinus_large.webp",
  },
  protagoras: {
    thumb: "/images/philosophers/protagoras_thumb.webp",
    large: "/images/philosophers/protagoras_large.webp",
  },
  pythagoras: {
    thumb: "/images/philosophers/pythagoras_thumb.webp",
    large: "/images/philosophers/pythagoras_large.webp",
  },
  quine: {
    thumb: "/images/philosophers/willard_van_orman_quine_thumb.webp",
    large: "/images/philosophers/willard_van_orman_quine_large.webp",
  },
  roger_bacon: {
    thumb: "/images/philosophers/roger_bacon_thumb.webp",
    large: "/images/philosophers/roger_bacon_large.webp",
  },
  rorty: {
    thumb: "/images/philosophers/richard_rorty_thumb.webp",
    large: "/images/philosophers/richard_rorty_large.webp",
  },
  rousseau: {
    thumb: "/images/philosophers/rousseau_thumb.webp",
    large: "/images/philosophers/rousseau_large.webp",
  },
  ruan_ji: {
    thumb: "/images/philosophers/ruan_ji_thumb.webp",
    large: "/images/philosophers/ruan_ji_large.webp",
  },
  russell: {
    thumb: "/images/philosophers/bertrand_russell_thumb.webp",
    large: "/images/philosophers/bertrand_russell_large.webp",
  },
  sartre: {
    thumb: "/images/philosophers/jean-paul_sartre_thumb.webp",
    large: "/images/philosophers/jean-paul_sartre_large.webp",
  },
  schelling: {
    thumb: "/images/philosophers/schelling_thumb.webp",
    large: "/images/philosophers/schelling_large.webp",
  },
  schopenhauer: {
    thumb: "/images/philosophers/schopenhauer_thumb.webp",
    large: "/images/philosophers/schopenhauer_large.webp",
  },
  scotus: {
    thumb: "/images/philosophers/johannes_duns_scotus_thumb.webp",
    large: "/images/philosophers/johannes_duns_scotus_large.webp",
  },
  seneca: {
    thumb: "/images/philosophers/seneca_thumb.webp",
    large: "/images/philosophers/seneca_large.webp",
  },
  shao_yong: {
    thumb: "/images/philosophers/shao_yong_thumb.webp",
    large: "/images/philosophers/shao_yong_large.webp",
  },
  socrates: {
    thumb: "/images/philosophers/socrates_thumb.webp",
    large: "/images/philosophers/socrates_large.webp",
  },
  spencer: {
    thumb: "/images/philosophers/spencer_thumb.webp",
    large: "/images/philosophers/spencer_large.webp",
  },
  spinoza: {
    thumb: "/images/philosophers/spinoza_thumb.webp",
    large: "/images/philosophers/spinoza_large.webp",
  },
  stirner: {
    thumb: "/images/philosophers/max_stirner_thumb.webp",
    large: "/images/philosophers/max_stirner_large.webp",
  },
  strauss: {
    thumb: "/images/philosophers/david_strauss_thumb.webp",
    large: "/images/philosophers/david_strauss_large.webp",
  },
  sun_tzu: {
    thumb: "/images/philosophers/sun_tzu_thumb.webp",
    large: "/images/philosophers/sun_tzu_large.webp",
  },
  thales: {
    thumb: "/images/philosophers/thales_thumb.webp",
    large: "/images/philosophers/thales_large.webp",
  },
  voltaire: {
    thumb: "/images/philosophers/voltaire_thumb.webp",
    large: "/images/philosophers/voltaire_large.webp",
  },
  wang_fuzhi: {
    thumb: "/images/philosophers/wang_fuzhi_thumb.webp",
    large: "/images/philosophers/wang_fuzhi_large.webp",
  },
  wang_tingxiang: {
    thumb: "/images/philosophers/wang_tingxiang_thumb.webp",
    large: "/images/philosophers/wang_tingxiang_large.webp",
  },
  wang_yangming: {
    thumb: "/images/philosophers/wang_yangming_thumb.webp",
    large: "/images/philosophers/wang_yangming_large.webp",
  },
  wei_yuan: {
    thumb: "/images/philosophers/wei_yuan_thumb.webp",
    large: "/images/philosophers/wei_yuan_large.webp",
  },
  wittgenstein: {
    thumb: "/images/philosophers/ludwig_wittgenstein_thumb.webp",
    large: "/images/philosophers/ludwig_wittgenstein_large.webp",
  },
  xenophanes: {
    thumb: "/images/philosophers/xenophanes_thumb.webp",
    large: "/images/philosophers/xenophanes_large.webp",
  },
  xuanzang: {
    thumb: "/images/philosophers/xuanzang_thumb.webp",
    large: "/images/philosophers/xuanzang_large.webp",
  },
  xunzi: {
    thumb: "/images/philosophers/xunzi_thumb.webp",
    large: "/images/philosophers/xunzi_large.webp",
  },
  yan_fu: {
    thumb: "/images/philosophers/yan_fu_thumb.webp",
    large: "/images/philosophers/yan_fu_large.webp",
  },
  yang_xiong: {
    thumb: "/images/philosophers/yang_xiong_thumb.webp",
    large: "/images/philosophers/yang_xiong_large.webp",
  },
  zeno: {
    thumb: "/images/philosophers/zenon_thumb.webp",
    large: "/images/philosophers/zenon_large.webp",
  },
  zeno_citium: {
    thumb: "/images/philosophers/zeno_thumb.webp",
    large: "/images/philosophers/zeno_large.webp",
  },
  zhiyi: {
    thumb: "/images/philosophers/zhiyi_thumb.webp",
    large: "/images/philosophers/zhiyi_large.webp",
  },
  zhou_dunyi: {
    thumb: "/images/philosophers/zhou_dunyi_thumb.webp",
    large: "/images/philosophers/zhou_dunyi_large.webp",
  },
  zhu_xi: {
    thumb: "/images/philosophers/zhu_xi_thumb.webp",
    large: "/images/philosophers/zhu_xi_large.webp",
  },
  zhuangzi: {
    thumb: "/images/philosophers/zhuangzi_thumb.webp",
    large: "/images/philosophers/zhuangzi_large.webp",
  },
};

export function getPhilosopherPortrait(id: string): { thumb: string; large: string } | undefined {
  return philosopherPortraits[id];
}
